### ISSUE TITLE
Could not build FiSH-irssi on CentOS release v6.7 (Final) + irssi v0.8.15

### ISSUE THREAD

**Issue by luckylittle** [falsovsky/FiSH-irssi#36]
[root@centos FiSH-irssi-master]# make
[ 16%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
In file included from /root/FiSH-irssi-master/src/FiSH.h:9,
                 from /root/FiSH-irssi-master/src/FiSH.c:2:
/root/FiSH-irssi-master/src/module.h:3:26: error: irssi-config.h: No such file or directory
In file included from /root/FiSH-irssi-master/src/module.h:5,
                 from /root/FiSH-irssi-master/src/FiSH.h:9,
                 from /root/FiSH-irssi-master/src/FiSH.c:2:
/root/irssi-0.8.15/src/common.h:66:4: error: #error uoff_t size not set
make[2]: *** [src/CMakeFiles/fish.dir/FiSH.c.o] Error 1
make[1]: *** [src/CMakeFiles/fish.dir/all] Error 2
make: *** [all] Error 2

**Comment by luckylittle** [comment]
Nevermind, i got it working on irssi-0.8.19:
[root@centos FiSH-irssi-master]# make
Scanning dependencies of target fish
[ 16%] Building C object src/CMakeFiles/fish.dir/base64.c.o
[ 33%] Building C object src/CMakeFiles/fish.dir/blowfish.c.o
[ 50%] Building C object src/CMakeFiles/fish.dir/inifile.c.o
[ 66%] Building C object src/CMakeFiles/fish.dir/DH1080.c.o
[ 83%] Building C object src/CMakeFiles/fish.dir/FiSH.c.o
[100%] Building C object src/CMakeFiles/fish.dir/password.c.o
Linking C shared module libfish.so
[100%] Built target fish
